#oc_web_agency_admin_post:
#    resource: "@OCWebAgencyBundle/Resources/config/routing/post.yml"
#    prefix:   /admin/post

oc_web_agency_homepage:
    path:     /
    defaults: { _controller: OCWebAgencyBundle:Home:index }

oc_web_agency_admin:
    path:    /admin/
    defaults: {_controller: OCWebAgencyBundle:Admin:admin}
    
oc_web_agency_search:
    path:    /search
    defaults: {_controller: OCWebAgencyBundle:Post:searchBar}

#oc_web_agency_handlesearch:
 #   path:    /handle_search
 #   defaults: {_controller: OCWebAgencyBundle:Post:handleSearch}

#**************************************************route front end ****************************************
#oc_web_agency_addcommentpost:
#    path:    /add_comment
#    defaults: {_controller: OCWebAgencyBundle:Post:addCommentPost}
oc_web_agency_addcommentpost:
    path:    /add_comment
    defaults: {_controller: OCWebAgencyBundle:Blog:addCommentPost}

oc_web_agency_blog:
    path:    /blog
    defaults: {_controller: OCWebAgencyBundle:Blog:blog }

#oc_web_agency_completepost:
#    path:    /post/{id}
#    defaults: {_controller: OCWebAgencyBundle:Post:post}

oc_web_agency_completepost:
    path:    /post/{id}
    defaults: {_controller: OCWebAgencyBundle:Blog:post}

oc_web_agency_createcontact:
    path: /contact
    defaults: {_controller: OCWebAgencyBundle:Contact:createContact}

oc_web_agency_sendmail:
    path: /email/{id}
    defaults: {_controller: OCWebAgencyBundle:Contact:sendMail}


#******** Route  pour Commment  *************************************************

admin_comment_index:
    path:     /admin/comment
    defaults: { _controller: OCWebAgencyBundle:Comment:index }
    methods:  GET

admin_comment_show:
    path:     /admin/comment/show/{id}
    defaults: { _controller: OCWebAgencyBundle:Comment:show }
    methods:  GET

admin_comment_new:
    path:     /admin/comment/new
    defaults: { _controller: OCWebAgencyBundle:Comment:new }
    methods:  [GET, POST]

admin_comment_edit:
    path:     /admin/comment/edit/{id}
    defaults: { _controller: OCWebAgencyBundle:Comment:edit }
    methods:  [GET, POST]

admin_comment_delete:
    path:     /admin/comment/delete/{id}
    defaults: { _controller: OCWebAgencyBundle:Comment:delete }
    methods:  DELETE

#******** Route  pour Post  *************************************************

admin_post_index:
    path:     /admin/post
    defaults: { _controller: OCWebAgencyBundle:Post:index }
    methods:  GET

admin_post_show:
    path:     /admin/post/show/{id}
    defaults: { _controller: OCWebAgencyBundle:Post:show }
    methods:  GET

admin_post_new:
    path:     /admin/post/new
    defaults: { _controller: OCWebAgencyBundle:Post:new }
    methods:  [GET, POST]

admin_post_edit:
    path:     /admin/post/edit/{id}
    defaults: { _controller: OCWebAgencyBundle:Post:edit }
    methods:  [GET, POST]

admin_post_delete:
    path:     /admin/post/delete/{id}
    defaults: { _controller: OCWebAgencyBundle:Post:delete }
    methods:  DELETE

#************************* route contact ******************************************************************
admin_contact_index:
    path:     /admin/contact
    defaults: { _controller: OCWebAgencyBundle:Contact:index }
    methods:  GET

admin_contact_show:
    path:     admin/contact/show/{id}
    defaults: { _controller: OCWebAgencyBundle:Contact:show }
    methods:  GET

admin_contact_new:
    path:     /admin/contact/new
    defaults: { _controller: OCWebAgencyBundle:Contact:new }
    methods:  [GET, POST]

admin_contact_edit:
    path:     admin/contact/edit/{id}
    defaults: { _controller: OCWebAgencyBundle:Contact:edit }
    methods:  [GET, POST]

admin_contact_delete:
    path:     admin/contact/delete/{id}
    defaults: { _controller: OCWebAgencyBundle:Contact:delete }
    methods:  DELETE

admin_contact_reply:
    path:     admin/contact/reply/{id}
    defaults: { _controller: OCWebAgencyBundle:Contact:reply }

admin_contact_responsemail:
    path:     admin/contact/response/{id}
    defaults: { _controller: OCWebAgencyBundle:Contact:responseMail }




#********************************************** route dashboard *******************************************

admin_comment_dashboard_delete:
    path:    /admin/comment/delete/{id}
    defaults: { _controller: OCWebAgencyBundle:Admin:deleteComment }

#******************** route pour mise a jour isSeen ********************************************
admin_updateIsSeen:
    path: /admin/comment/update/{id}
    defaults: { _controller: OCWebAgencyBundle:Admin:updateIsSeen}

#************************ route page ********************************************************

admin_page_index:
    path:     /admin/page
    defaults: { _controller: OCWebAgencyBundle:Page:index }
    methods:  GET

admin_page_show:
    path:     /admin/page/show/{id}
    defaults: { _controller: OCWebAgencyBundle:Page:showAdmin }
    methods:  GET

admin_page_new:
    path:     /admin/page/new
    defaults: { _controller: OCWebAgencyBundle:Page:new }
    methods:  [GET, POST]

admin_page_edit:
    path:     /admin/page/edit/{id}
    defaults: { _controller: OCWebAgencyBundle:Page:edit }
    methods:  [GET, POST]

admin_page_delete:
    path:     /admin/page/delete/{id}
    defaults: { _controller: OCWebAgencyBundle:Page:delete }
    methods:  DELETE

oc_web_agency_front_page:
    path: /page/{slug}
    defaults: { _controller: OCWebAgencyBundle:Page:showPage }
    methods: GET

oc_web_agency_back_page:
    path: /admin/page/show/{slug}
    methods: GET



#************************ route item ********************************************************

admin_item_index:
    path:     /admin/item
    defaults: { _controller: "OCWebAgencyBundle:Item:index" }
    methods:  GET

admin_item_show:
    path:     /admin/item/{id}/show
    defaults: { _controller: "OCWebAgencyBundle:Item:show" }
    methods:  GET

admin_item_new:
    path:     /admin/item/new
    defaults: { _controller: "OCWebAgencyBundle:Item:new" }
    methods:  [GET, POST]

admin_item_edit:
    path:     /admin/item/{id}/edit
    defaults: { _controller: "OCWebAgencyBundle:Item:edit" }
    methods:  [GET, POST]

admin_item_delete:
    path:     /admin/item/{id}/delete
    defaults: { _controller: "OCWebAgencyBundle:Item:delete" }
    methods:  DELETE

#***************************** route newsLetter *******************************************

oc_web_agency_newsletter:
    path: /newsletter
    defaults: {_controller: OCWebAgencyBundle:Newsletter:newUser}

#***************************** route post category  *******************************************

admin_category_index:
    path:     /admin/category
    defaults: { _controller: "OCWebAgencyBundle:Category:index" }
    methods:  GET

admin_category_show:
    path:     /admin/category/{id}/show
    defaults: { _controller: "OCWebAgencyBundle:Category:show" }
    methods:  GET

admin_category_new:
    path:     /admin/category/new
    defaults: { _controller: "OCWebAgencyBundle:Category:new" }
    methods:  [GET, POST]

admin_category_edit:
    path:     /admin/category/{id}/edit
    defaults: { _controller: "OCWebAgencyBundle:Category:edit" }
    methods:  [GET, POST]

admin_category_delete:
    path:     /admin/category/{id}/delete
    defaults: { _controller: "OCWebAgencyBundle:Category:delete" }
    methods:  DELETE


