oc_web_agency_admin_post:
    resource: "@OCWebAgencyBundle/Resources/config/routing/post.yml"
    prefix:   /admin/post

oc_web_agency_homepage:
    path:     /
    defaults: { _controller: OCWebAgencyBundle:Home:index }

oc_web_agency_admin:
    path:    /admin/
    defaults: {_controller: OCWebAgencyBundle:Admin:admin}

#******** Route fosuser pour Commment  *************************************************

admin_comment_index:
    path:     /admin/comment
    defaults: { _controller: "OCWebAgencyBundle:Comment:index" }
    methods:  GET

admin_comment_show:
    path:     /admin/comment/show/{id}
    defaults: { _controller: "OCWebAgencyBundle:Comment:show" }
    methods:  GET

admin_comment_new:
    path:     /admin/comment/new
    defaults: { _controller: "OCWebAgencyBundle:Comment:new" }
    methods:  [GET, POST]

admin_comment_edit:
    path:     /admin/comment/edit/{id}
    defaults: { _controller: "OCWebAgencyBundle:Comment:edit" }
    methods:  [GET, POST]

admin_comment_delete:
    path:     /admin/comment/delete/{id}
    defaults: { _controller: "OCWebAgencyBundle:Comment:delete" }
    methods:  DELETE

#******** Route fosuser pour Post  *************************************************

admin_post_index:
    path:     /admin/post
    defaults: { _controller: "OCWebAgencyBundle:Post:index" }
    methods:  GET

admin_post_show:
    path:     /admin/post/show/{id}
    defaults: { _controller: "OCWebAgencyBundle:Post:show" }
    methods:  GET

admin_post_new:
    path:     /admin/post/new
    defaults: { _controller: "OCWebAgencyBundle:Post:new" }
    methods:  [GET, POST]

admin_post_edit:
    path:     /admin/post/edit/{id}
    defaults: { _controller: "OCWebAgencyBundle:Post:edit" }
    methods:  [GET, POST]

admin_post_delete:
    path:     /admin/post/delete/{id}
    defaults: { _controller: "OCWebAgencyBundle:Post:delete" }
    methods:  DELETE
#********************************************** route dashboard *******************************************

admin_comment_dashboard_delete:
    path:    /admin/comment/delete/{id}
    defaults: { _controller: "OCWebAgencyBundle:Admin:deleteComment" }