imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    images_directory: '%kernel.root_dir%/../web/uploads/images'
    # Ajout Abdel
    app.path.product_images: /uploads/images
framework:
    templating:
        engines: ['twig']
    #esi: ~
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # Ajout Abdel
    form_themes:
        - bootstrap_3_layout.html.twig
        - 'VichUploaderBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# FOSUser Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: OC\WebAgencyBundle\Entity\User
    from_email:
        address: "christian.yvan@gmail.com"  #"%mailer_user%"
        sender_name: "Test fosuser"          #"%mailer_user%"

# Ajout Abdel
# Stof\DoctrineExtensionsBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

# vich/uploader-bundle configuration
vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/../web%app.path.product_images%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
# Ajout Abdel
services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }
# Ajout Abdel           
fos_ck_editor:
    #configs:
        #config:
            #my_toolbar: my_toolbar_1

        #toolbars:
            #configs:
                #my_toolbar_1: [ [ "Source", "-", "Save" ], "/", [ "Anchor" ], "/", [ "Maximize" ] ]
                #my_toolbar_2: [ [ "Source" ], "/", [ "Anchor" ], "/", [ "Maximize" ] ]
    configs:
        my_config_1:
            toolbar: "my_toolbar_1"
            #uiColor: "#000000"
        my_config_2:
            toolbar: "my_toolbar_2"
            #uiColor: "#ffffff"
        my_config_2:
            toolbar: "my_toolbar_1"
            #uiColor: "#cccccc"
    toolbars:
        configs:
            my_toolbar_1: [ [ "Source", "-", "Save" ], "/", [ "Maximize" ] ]
            my_toolbar_2: [ [ "Source" ], "/", [ "Anchor" ], "/", [ "Maximize" ] ]
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: false                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: pagination/bootstrap4_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
welp_mailchimp:
    api_key: fd8e42c4b8c664d4be7922c271d7ffeb-us19
    list_provider: 'welp_mailchimp.list_provider'
    lists:
        listId1:
            # provider used in full synchronization
            subscriber_provider: 'wagency.provider1'
            # webhook secret to secure webhook between MailChimp & your app
            webhook_secret: '@webagency2018'
            # The webhook url to be registered to the MailChimp list
            webhook_url: 'http://agenceweb.yassir-montet.pxgp.fr/app_dev.php/mailchimp/webhook/endpoint'
            # optional merge tags you want to synchronize
            merge_fields:
                -
                    tag: FNAME
                    name: First Name
                    type: text
                    public: true
                -
                    tag: LNAME
                    name: Last Name
                    type: text
                    public: true