oc_web_agency_item:
    resource: "@OCWebAgencyBundle/Controller/ItemController.php"
    type:     annotation

oc_web_agency_contact:
    resource: "@OCWebAgencyBundle/Controller/ContactController.php"
    type:     annotation


oc_web_agency_comment:
    resource: "@OCWebAgencyBundle/Controller/CommentController.php"
    type:     annotation

oc_web_agency_post:
    resource: "@OCWebAgencyBundle/Controller/PostController.php"
    type:     annotation

oc_web_agency:
    resource: "@OCWebAgencyBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

oc_mailchimp_webhook:
    resource: "@WelpMailchimpBundle/Resources/config/routing.yml"
    prefix:   /mailchimp
