OC\WebAgencyBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: OC\WebAgencyBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        email:
            type: string
            length: 255
        subject:
            type: string
            length: 255
        message:
            type: string
            length: 255
    lifecycleCallbacks: {  }
